DeerIQApp/force-app/main/default/objects/Hunt_Area__c/Hunt_Area__c.object-meta.xml
<CustomObject>
    <label>Hunt Area</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hunt Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeerIQApp/force-app/main/default/objects/Pin__c/Pin__c.object-meta.xml
<CustomObject>
    <label>Pin</label>
    <nameField>
        <label>Pin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeerIQApp/force-app/main/default/objects/Pin__c/fields/Hunt_Area__c.field-meta.xml
<CustomField>
    <fullName>Hunt_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hunt Area</label>
    <referenceTo>Hunt_Area__c</referenceTo>
    <relationshipLabel>Pins</relationshipLabel>
    <relationshipName>Pins</relationshipName>
    <type>Lookup</type>
</CustomField>

DeerIQApp/force-app/main/default/classes/AreaMapController.cls
public with sharing class AreaMapController {
    @AuraEnabled(cacheable=true)
    public static List<Pin__c> getPinsForArea(Id huntAreaId) {
        return [
            SELECT Id, Name, Geolocation__Latitude__s, Geolocation__Longitude__s 
            FROM Pin__c 
            WHERE Hunt_Area__c = :huntAreaId 
                AND Geolocation__Latitude__s != null
                AND Geolocation__Longitude__s != null
        ];

    }
}